### PR TITLE
Support Ubuntu 20.04

### PR DESCRIPTION
**Pull request by anders-larsson**

### CODE REVIEW

**Comment by anders-larsson** [comment]
It appears PuppetLabs has decided not to provide a puppet5 package for 20.04. OK to remove Puppet 5 from Ubuntu 20.04 tests?

**Comment by ghoneycutt** [comment]
@anders-larsson Awesome! Thank you!

Looks like Travis had a time out with one of the tests. Restarting and once it passes, this is good to be merged.

**Comment by ghoneycutt** [comment]
Aha.. that was the error, because the packages do not exist. Yes, go ahead and remove from Travis and leave a comment saying that Ubuntu 20.04 is not supported on Puppet 5.

**Comment by anders-larsson** [comment]
Where do you want this comment added? I'll fix it tomorrow.

Thanks.

**Comment by ghoneycutt** [comment]
Hi, Just add it to travis in place of the puppet5 section you are removing.

**Comment by anders-larsson** [comment]
@ghoneycutt Pull request ready for another review btw :)

**Comment by ghoneycutt** [comment]
Brilliant! Thanks @anders-larsson

**Comment by ghoneycutt** [comment]
Released in v2.6.0

**Pull request merged**
